### ISSUE TITLE
Hackintool cannot discriminate VoodooInput.kext used in different kexts 

### ISSUE THREAD

**Issue by mackonsti** [headkaze/Hackintool#156]
Hello @headkaze thank you once more for your continuing support of the tool.

I have been using on my Lenovo IdeaPad laptop the [VoodooI2C.kext](https://github.com/VoodooI2C/VoodooI2C/releases) (hasn't been updated recently, though) for ELAN trackpad, and inside there is a **VoodooInput.kext** plugin that has the same name with [VoodooPS2Controller.kext](https://github.com/acidanthera/VoodooPS2/releases) own plugin. To be honest, I am not sure if it's the same code/plugin and just an older version.

I have _not_ had a conflict in Hackintool in the past as far as I can remember; but **if there's a kext used in two different bundles, is it expected behaviour for Hackintool to _not_ be able to separate the two?** I guess if they have the same bundle ID, there's no way correct?

OpenCore 0.7.5 is used and **VoodooInput.kext** is defined and loaded as being part of **VoodooI2C.kext** structure (plugin) Moreover, these are the bundle identifiers and they have the same string...

```
VoodooPS2Controller v2.2.7 Release:
	<key>CFBundleIdentifier</key>
	<string>me.kishorprins.VoodooInput</string>

VoodooI2C v2.6.5 Release:
	<key>CFBundleIdentifier</key>
	<string>me.kishorprins.VoodooInput</string>
```

I know I am replying to my own question, but thought of making you aware of this issue.
![Hackintool VoodooInput](https://user-images.githubusercontent.com/1313613/142743365-15839912-bdad-4360-98c4-295e49aac24a.png)
**P.S.** I saw you updated a new version reading IDs for USB devices; My BT is Intel as 0x8087 and shows ????? by the way (in System > Peripherals tab).

Thank you again!

**Comment by headkaze** [comment]
Thanks for the heads up on the BT issue. That should be fixed soon.

Can you please post the output for the following command:
`kextstat -l`

**Comment by headkaze** [comment]
> **P.S.** I saw you updated a new version reading IDs for USB devices; My BT is Intel as 0x8087 and shows ????? by the way (in System > Peripherals tab).

Please let me know if 3.6.9 fixes this isuse

**Comment by mackonsti** [comment]
Hello @headkaze so here we are:

```
% kextstat -l | grep -vi apple

Executing: /usr/bin/kmutil showloaded --list-only
No variant specified, falling back to release
   48    5 0                  0x2e000    0x2e000    as.vit9696.Lilu (1.5.7) E42A54DC-9082-35EC-93BC-08AD09861180 <8 6 5 3 2 1>
   49    2 0                  0x1a000    0x1a000    as.vit9696.VirtualSMC (1.2.7) 9DAADEEB-D155-3EEC-AFDF-2F05E221EA01 <48 13 8 6 5 3 1>
   51    0 0                  0x18000    0x18000    ru.usrsse2.SMCBatteryManager (1.2.7) 372230D7-5D91-34A2-A2A7-ACA96A4F8C86 <50 49 48 13 8 6 5 3 1>
   52    0 0                  0x80000    0x80000    as.vit9696.WhateverGreen (1.5.5) 9F7BED07-35BC-3306-88A5-D5DADBD42A53 <48 14 8 6 5 3 2 1>
   54    1 0                  0xb000     0xb000     com.alexandred.VoodooI2CServices (1) DBFA5EBE-2783-30ED-8E39-5829C42D6832 <5 3>
   55    0 0                  0xf000     0xf000     as.vit9696.SMCProcessor (1.2.7) 14D4674E-0AA9-3311-A95A-AF9106AF7E8C <49 48 13 8 6 5 3 2 1>
   66    1 0                  0x27000    0x27000    org.coolstar.VoodooGPIO (1.1) 7ED39A4D-2EFD-35AE-9BC6-6215C17D93F1 <13 6 5 3>
   67    1 0                  0x19000    0x19000    as.acidanthera.voodoo.driver.PS2Controller (2.2.7) 07FB2C37-40D6-37AF-965F-6351582195B7 <13 8 6 5 3 1>
   70    1 0                  0x3b000    0x3b000    com.alexandred.VoodooI2C (2.6.5) 748C2CC2-07FD-3FD5-8E86-874C73317356 <66 61 54 14 13 6 5 3 1>
   80    0 0                  0xf11000   0xf11000   com.zxystd.AirportItlwm (2.1.0) 5068ABCF-11AA-3C4D-BDD3-CBA2C66B08BB <79 46 14 6 5 3 1>
   83    0 0                  0xc000     0xc000     me.kishorprins.VoodooI2CELAN (1) D3EE7E6D-F3FB-3A39-BD36-7C4BCF972E9B <70 61 13 6 5 3>
  101    0 0                  0x19000    0x19000    me.kishorprins.VoodooInput (1.1.1) 2DBFF028-3A8F-37C9-A5D7-B435F5AA516F <61 6 5 3>
  111    0 0                  0x2bd000   0x2bd000   com.zxystd.IntelBluetoothFirmware (2.0.1) 179C77D4-214E-3A31-808E-1BC03491AC55 <22 6 5 3>
  115    0 0                  0xd000     0xd000     as.acidanthera.voodoo.driver.PS2Keyboard (2.2.7) A7EFC06D-0A5C-3277-9EC1-E182089690D9 <67 61 8 6 5 3 1>
  134    0 0xffffff7f9cc6a000 0x2000     0x2000     com.intel.driver.EnergyDriver (3.7.0) 35E739F9-BF6C-3024-A67C-750711B3FB64 <8 6 5 3>
```

It seems that the ID `me.kishorprins.VoodooInput` is the same across both kexts, as reported earlier...

Secondly, I am sorry to report that on both my hacks, Hackintool still shows `????` instead of Intel Corporation in the Peripherals tab 😞 Vendor ix 0x8087. Is it a display encoding issue or a USB ID cross-reference issue?
![Still Question Marks](https://user-images.githubusercontent.com/1313613/142769181-a4a6f69c-bee8-41b3-afcf-778866dbf940.png)
Thanks for your time.

**Comment by headkaze** [comment]
I don't think I can distinguish between two different kexts if the name and bundle id are the same.

Please try 3.7.0 regarding the BT device detection.

**Comment by mackonsti** [comment]
> I don't think I can distinguish between two different kexts if the name and bundle id are the same.

Yes, I thought that much. Anyway, thanks for looking at this issue reported.

> Please try 3.7.0 regarding the BT device detection.

Works now, thank you. I guess we can close this ticket. Thanks again!

![Hackintool BTLE](https://user-images.githubusercontent.com/1313613/142779511-56d229dc-0325-4ce2-bcb3-854b247dae13.png)
